name: 'hood_data'
version: '1.0.0'
config-version: 2
profile: 'hood_data'
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
models:
  hood_data:
    staging:
      +materialized: view
