name: move DAGs to GCS folder

on:
  push:
    paths:
      - 'airflow/**'
      - '.github/workflows/airflow-dags.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    env:
      AIRFLOW_BUCKET: us-central1-hood-data-8aaf55e2-bucket
    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - uses: 'google-github-actions/setup-gcloud@v1'
      name: 'Set up Cloud SDK'

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Sync DAGs to Airflow
      run: |
        gsutil -m rsync -d -c -r airflow/dags gs://$AIRFLOW_BUCKET/dags
        gsutil -m rsync -d -c -r airflow/plugins gs://$AIRFLOW_BUCKET/plugins
